import React from 'react';
import {
  BankIcon,
  BookOpenIcon,
  CarIcon,
  CardPayIcon,
  CellphoneIcon,
  CoDiIcon,
  EthosQRIcon,
  FilmIcon,
  GamepadIcon,
  LampIcon,
  MoneyIcon,
  PawIcon,
  PeopleIcon,
  PersonCloudIcon,
  PersonalProvisionIcon,
  PhoneIcon,
  TimeIcon,
  UmbrellaIcon,
  UmbrellaStarIcon,
  WaterIcon,
} from 'assets/svg';

export const SHORTCUTS_ICONS = {
  personalDisposition: <PersonalProvisionIcon />,
  payCard: <CardPayIcon />,
  scheduledPayments: <TimeIcon />,
  ethosCreditQR: <EthosQRIcon />,
  collectContacts: <PeopleIcon />,
  collectViaCODI: <CoDiIcon />,
  collectInCash: <MoneyIcon />,
  personalProject: <PersonCloudIcon />,
  electricityAndGas: <LampIcon />,
  water: <WaterIcon />,
  topUps: <CellphoneIcon />,
  entertainment: <GamepadIcon />,
  governmentPayments: <BankIcon />,
  tollsAndParkingMeters: <CarIcon />,
  telecommunications: <PhoneIcon />,
  catalogSales: <BookOpenIcon />,
  ethosPlusBenefits: <UmbrellaIcon />,
  ethosProBenefits: <UmbrellaStarIcon />,
  '2x1Cinema': <FilmIcon />,
  petBenefits: <PawIcon />,
};
